work_factors:
  '{{cookiecutter.project_type0}}':
    complex:
    - '{{cookiecutter.project_type0_complex_factor_0}}'
    - '{{cookiecutter.project_type0_complex_factor_1}}'
    - '{{cookiecutter.project_type0_complex_factor_2}}'
    - '{{cookiecutter.project_type0_complex_factor_3}}'
    - '{{cookiecutter.project_type0_complex_factor_4}}'
    simple:
    - '{{cookiecutter.project_type0_a_simple_factor_0}}'
    - '{{cookiecutter.project_type0_a_simple_factor_1}}'
    - '{{cookiecutter.project_type0_a_simple_factor_2}}'
    - '{{cookiecutter.project_type0_a_simple_factor_3}}'
    - '{{cookiecutter.project_type0_a_simple_factor_4}}'
  '{{cookiecutter.project_type1}}':
    complex:
    - '{{cookiecutter.project_type1_complex_factor_0}}'
    - '{{cookiecutter.project_type1_complex_factor_1}}'
    - '{{cookiecutter.project_type1_complex_factor_2}}'
    - '{{cookiecutter.project_type1_complex_factor_3}}'
    - '{{cookiecutter.project_type1_complex_factor_4}}'
    simple:
    - '{{cookiecutter.project_type1_a_simple_factor_0}}'
    - '{{cookiecutter.project_type1_a_simple_factor_1}}'
    - '{{cookiecutter.project_type1_a_simple_factor_2}}'
    - '{{cookiecutter.project_type1_a_simple_factor_3}}'
    - '{{cookiecutter.project_type1_a_simple_factor_4}}'
